// Copyright 2025 Fondazione LINKS

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at

//     http://www.apache.org/licenses/LICENSE-2.0

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "ISIS.h"
#include <atomic>

long  idx_ISIS; // Global variable, for benchmarking purposes


//==============================================================================
// Preprocessing_ISIS - Preprocessing function (PreprocessingProve^HISIS_ISIS).
//      It takes as input (s0, B_goth_s, r0, B_goth_r)
//      with B_goth_s ≥ ||s|| and B_goth_r ≥ ||r||.
//      It returns s and r such that B_goth_s = ||s|| and B_goth_r = ||r||.
//
// Inputs:
// - s0:            vector s0 ∈ Z^((m+2)·d)_(q_hat)
// - r0:            vector r0 ∈ Z^(|idx_hid|·h + ℓr·d)_(q_hat)
// - B_goth_s2:     bound  B_goth_s^2 ∈ Z≥0 (it is a scalar)
// - B_goth_r2:     bound  B_goth_r^2 ∈ Z≥0 (it is a scalar)
// - num_idx_hid:   number of undisclosed attributes (hidden)
//
// Output:
// - s:             vector s ∈ Z^((m+2)·d + d_hat)_(q_hat)
// - r:             vector r ∈ Z^(|idx_hid|·h + ℓr·d + d_hat)_(q_hat)
//==============================================================================
// NOTE: zero padding of P, s, C, r already done in H_VerPres
void  Preprocessing_ISIS(vec_zz_p& s, vec_zz_p& r, const vec_ZZ& s0, const vec_ZZ& r0, const ZZ& B_goth_s2, const ZZ& B_goth_r2, const long &num_idx_hid)
{
    // NOTE: assuming that current modulus is q2_hat (not q0)
    long    i;
    ZZ      diff; //a1, a2, a3, a4;
    vec_ZZ  a;

    const long  m2d     = (m0 + 2)*d0;    // (m+2)·d
    const long  idxhlrd = (num_idx_hid * h0) + (lr0 * d0); //|idx_hid|·h + ℓr·d

    // diff = B_goth_s^2 − ||s||^2
    diff = (B_goth_s2 - Norm2(s0));

    if (diff < 0)
    {
        cout << "ERROR! (B_goth_s^2 - ||s||^2) must be positive: " << diff << endl;
        assert(diff >= 0);
    }
    else if (diff == 0)
    {
        cout << "WARNING! (B_goth_s^2 - ||s||^2) == 0 " << endl;
    }

    // diff = diff % q2_hat;
    // NOTE: diff mod q2_hat, to speed up sum_of_four_squares


    // 1. (a1, a2, a3, a4) ← SumOfFourSquares(B_goth_s^2 − ||s||^2),   (a1, a2, a3, a4) ∈ Z^4
    // sum_of_four_squares(a1, a2, a3, a4, diff);
    // NOTE: sum_of_four_squares (too slow) replaced with fast_sum_of_squares
    fast_sum_of_squares(a, diff);

    // 2. a ← (a1, a2, a3, a4, 0, ... , 0),  a ∈ Z^(d_hat)
    // NOTE: add d_hat − 4 zeros

    // 3. s ← (s0, a),   s ∈ Z^((m+2)·d + d_hat)_(q_hat)
    s = conv<vec_zz_p>(s0);

    for(i=0; i<a.length(); i++)
    {
        s[m2d+i] = conv<zz_p>(a[i]);
    }

    // 4. P ← [P0,  0_(d × d_hat)],   P ∈ Z^[d × (m+2)·d + d_hat]_(q_hat)


    // diff = B_goth_r^2 − ||r||^2
    diff = (B_goth_r2 - Norm2(r0));

    if (diff < 0)
    {
        cout << "ERROR! (B_goth_r^2 - ||r||^2) must be positive: " << diff << endl;
        assert(diff >= 0);
    }
     else if (diff == 0)
    {
        cout << "WARNING! (B_goth_r^2 - ||r||^2) == 0 " << endl;
    }

    // diff = diff % q2_hat;
    // NOTE: diff mod q2_hat, to speed up sum_of_four_squares


    // 5. (b1, b2, b3, b4) ← SumOfFourSquares(B_goth_r^2 − ||r||^2),   (b1, b2, b3, b4) ∈ Z^4
    // sum_of_four_squares(a1, a2, a3, a4, diff);
    // NOTE: sum_of_four_squares (too slow) replaced with fast_sum_of_squares
    fast_sum_of_squares(a, diff);

    // 6. b ← (b1, b2, b3, b4, 0, ... , 0),  b ∈ Z^(d_hat)
    // NOTE: add d_hat − 4 zeros

    // 7. r ← (r0, b),   r ∈ Z^(|idx_hid|·h + ℓr·d + d_hat)_(q_hat)
    r = conv<vec_zz_p>(r0);

    for(i=0; i<a.length(); i++)
    {
        r[idxhlrd+i] = conv<zz_p>(a[i]);
    }

    // 8. C ← [C0,  0_(d × d_hat)],   C ∈ Z^[d × ((ℓm+ℓr)·d + d_hat)]_(q_hat)

    // 9. return (P, s, C, r)
}


//==============================================================================
// Prove_ISIS   -   Computes the Commitment (Prove^HISIS_ISIS).
//                  This function takes as input crs, x, and w.
//                  If all the checks pass, it returns the proof π.
//
// Inputs:
// - nonce:         random cryptographic nonce (challenge) generated by Verifier
// - seed_crs:      initial public seed for crs structure
// - crs:           structure crs_ISIS, generated by Hcrs from seed_crs
// - ipk_bytes:     serialized Issuer Public Key
// - (P, C, mex, B_f,
//    Bounds, aux): they correspond to x
// -  w0:           it contains the vectors (s0, r0, u0)
// -  idx_hid:      indexes of undisclosed attributes (hidden)
//
// Output:
// -  Pi_ptr:       pointer to proof (π) data
//==============================================================================
void Prove_ISIS(uint8_t** Pi_ptr, const uint8_t* nonce, const uint8_t* seed_crs, const CRS_t& crs, const uint8_t* ipk_bytes, const mat_zz_p& P, const mat_zz_p& C, const vec_zz_p& mex, const mat_zz_p& B_f, const vec_ZZ& Bounds, const long& aux, const Vec<vec_ZZ>& w0, const vec_UL &idx_hid)
{
    // NOTE: assuming that current modulus is q2_hat (not q0)

    ulong           poly_off, idx, i, j, k, t;
    long            rst, b1, b2, b3;
    // Mat<zz_pX>      B;
    vec_zz_pX       g;
    zz_p            acc_coeff, product_scalar;
    vec_zz_pX       A_hat_mu, B_hat_mu, C_hat_mu, L_hat_mu;
    // vec_zz_pX       c_r_j, p_j, Beta_j, r_j, h_part1, h_part2, d_1, D2_y, s_2;
    vec_zz_pX       mu, tmp_vec, y;
    vec_zz_pX       sigma_s_1, acc_vec, sigma_y_1;
    vec_zz_pX       s, r, u, s_1, y_1, y_2, y_3, c_s1, c_s2;
    zz_pX           b_s2, b_y2, mu_y_acc, product_poly, scratch_poly, c, y3y0, y4y1, y5y2, s3y0, s4y1, s5y2, y3s0, y4s1, y5s2;
    // zz_pX           h_part3, h_part4, h_part5;
    zz_pX           quad_s, quad_r, quad_u, acc, delta_1, delta_2, delta_3, f1;
    Mat<zz_pX>      A_hat, B_hat, C_hat, L_hat;
    // Mat<zz_pX>      sigma_p_, sigma_Beta_, sigma_c_r_, e_, sigma_e_, D2_2_1;
    // Mat<zz_pX>      sigma_r_, sigma_r_s_, sigma_r_r_, sigma_r_u_;
    mat_zz_p        gamma;
    // mat_zz_p        R_goth_old, C_r, C_m;
    vec_zz_p        coeffs_s, coeffs_r, coeffs_s1, coeffs_y3, coeffs_R_goth_mult_s1;
    //vec_zz_p        ones;
    //vec_zz_pX       coeffs_ones, u_m_ones, sigma_u_m_ones, sigma_ones;
    vec_zz_pX       A1_s1, sigma_s, sigma_r, sigma_u;
    vec_zz_p        m_C;
    // vec_zz_p        e_tmp;
    // zz_p            d_0;
    RR              alpha_i;
    ZZ              B_goth_s2,   B_goth_r2;
    zz_p            sums, B_goth_s2_p, B_goth_r2_p;
    size_t          coeff_off, len_a1, len_idx_hid, len_mex, len_Bounds, len_aux, max_len;
    size_t          len_t_A, len_t_y, len_t_g, len_w, len_z_3, len_h;
    size_t          len_t, len_f0, len_z_1, len_z_2, len_valid, len_Pi;
    uint8_t        *buffer, *Pi_bytes0, *Pi_bytes;
    vector<size_t>  lengths;
    PROOF_I_t       Pi;



    // Initialise constants
    const ulong     num_idx_hid = idx_hid.length(); // number of undisclosed attributes (hidden)
    const ulong     num_idx_pub = l0 - num_idx_hid; // number of disclosed attributes (revealed)
    const ulong     n           = n_ISIS;
    const ulong     m1          = (((m0+2)*d0 + (num_idx_hid*h0 + lr0*d0) + t0 + 2*d_hat) / d_hat); // m_1 for Π^ISIS_NIZK
    const ulong     m2          = m2_ISIS;                                                          // m_2 for Π^ISIS_NIZK
    const ulong     m2ddd       = ((m0 + 2)*d0 + d_hat)/d_hat;              // ((m+2)·d + d^)/d^
    const ulong     idxhlrdd    = (num_idx_hid * h0) + (lr0 * d0) + d_hat;  //|idx_hid|·h + ℓr·d + d^
    const ulong     idxhlrddd   = idxhlrdd/d_hat;
    const ulong     n256        = (256/d_hat);
    const ulong     t_d         = (t0/d_hat);
    //const ulong     m1_n256_tau = 2*m1 + 2*(n256 + tau_ISIS);
    const int       nbits0      = ceil(log2(conv<double>(q0-1)));
    const int       nbits       = ceil(log2(conv<double>(q2_hat-1)));
    const ulong     c_offset    = num_idx_pub * h0;
    const ulong     t_d_offset  = m2ddd + idxhlrddd;
    HASH_STATE_t    state0;
    HASH_STATE_t    state;
    product_poly.SetLength(d_hat);
    scratch_poly.SetLength(d_hat);

    #ifdef ENABLE_TIMING_PROVE
    double t1 = GetWallTime();
    #endif
    // Initialise the "goth" constants
    // M1 := exp(sqrt(2(λ+1)/log e) * 1/α_1 + 1/2α_1^2
    // M2 := exp(sqrt(2(λ+1)/log e) * 1/α_2 + 1/2α_2^2
    // M3 := exp(sqrt(2(λ+1)/log e) * 1/α_3 + 1/2α_3^2
    alpha_i = RR(alpha_1);
    const RR  M_1 = exp( sqrt( RR(2*(lambda0 + 1)) / log2e_Const ) * 1/alpha_i + 1/(2*sqr(alpha_i)));
    alpha_i = RR(alpha_2);
    const RR  M_2 = exp( sqrt( RR(2*(lambda0 + 1)) / log2e_Const ) * 1/alpha_i + 1/(2*sqr(alpha_i)));
    alpha_i = RR(alpha_3);
    const RR  M_3 = exp( sqrt( RR(2*(lambda0 + 1)) / log2e_Const ) * 1/alpha_i + 1/(2*sqr(alpha_i)));


    // 1. Retrieve (A_1, A_2, B_y, B_g, b) ← crs_ISIS
    // A_1     = crs[0];    // ∈ R^^(n x m1)_(q_hat)
    // A_2     = crs[1];    // ∈ R^^(n x m2)_(q_hat)
    // B_y     = crs[2];    // ∈ R^^(256/d^ x m2)_(q_hat)
    // B_g     = crs[3];    // ∈ R^^(tau_ISIS x m2)_(q_hat)
    // b       = crs[4][0]; // ∈ R^^(m2)_(q_hat)         NOTE: b in crs is a (1 x m_2) matrix

    // 2. (P, C, mex, B_f, Bounds, aux) ← x
    // NOTE: directly provided as inputs

    // 3. (B_goth_s^2, B_goth_r^2) ← Bounds,   (B_goth_s^2, B_goth_r^2) ∈ Z^2
    B_goth_s2 = Bounds[0];
    B_goth_r2 = Bounds[1];
   

    // B_goth = sqrt(B_goth_s^2 + B_goth_r^2 + t0)
    const RR B_goth = sqrt( conv<RR>( B_goth_s2 + B_goth_r2 + t0 ) );

    B_goth_s2_p = conv<zz_p>(B_goth_s2);
    B_goth_r2_p = conv<zz_p>(B_goth_r2);

    // s1_goth = alpha_1*nu0*B_goth
    // s2_goth = alpha_2*nu0*sqrt(m2*d_hat)
    // s3_goth = alpha_3*w_max(lambda0)*B_goth
    const RR  s1_goth = RR(alpha_1 * nu0) * B_goth;
    const RR  s2_goth = RR(alpha_2 * nu0) * sqrt( RR(m2*d_hat) );
    const RR  s3_goth = RR(alpha_3 * w_max) * B_goth;
    const double s1_goth_d = conv<double>(s1_goth);
    const double s2_goth_d = conv<double>(s2_goth);
    const double s3_goth_d = conv<double>(s3_goth);
    // const uint tau_folded = tau_ISIS / 2;
    vector<TernaryCoeffStructure> R_goth(256);
    TernaryCoeffStructure s2_raw;

    // 4. (s0, r0, u0) ← w0
    // s0 = w0[0];  // s0 ∈ Z^((m+2)·d)
    // r0 = w0[1];  // r0 ∈ Z^(|idx_hid|·h + ℓr·d)
    // u0 = w0[2];  // u0 ∈ {0,1}^t

    // 5. (P, s, C, r) ← PreprocessingProve^HISIS_ISIS (P, s, B_goth_s, C, r, B_goth_r)
    // P ∈ Z^[d × (m+2)·d + d_hat]_(q_hat)
    // s ∈ Z^((m+2)·d + d_hat)_(q_hat)
    // C ∈ Z^[d × ((ℓm+ℓr)·d + d_hat)]_(q_hat)
    // r ∈ Z^(|idx_hid|·h + ℓr·d + d_hat)_(q_hat)
    Preprocessing_ISIS(coeffs_s, coeffs_r, w0[0], w0[1], B_goth_s2, B_goth_r2, num_idx_hid);

    // 6. s ← Coeffs^−1(s0)
    CoeffsInvHat(s, coeffs_s, m2ddd);     // s ∈ R^^(((m+2)·d+d_hat)/d_hat)_(q_hat)

    //    r ← Coeffs^−1(r0)
    CoeffsInvHat(r, coeffs_r, idxhlrddd); // r ∈ R^^((|idx_hid|·h + ℓr·d + d_hat)/d_hat)_(q_hat)

    //    u ← Coeffs^−1(u0)
    CoeffsInvHat(u, conv<vec_zz_p>(w0[2]), t_d);    // u ∈ R^^(t/d_hat)_(q_hat)


    // 7. s_1 ← (s, r, u),   s_1 ∈ R^^(m1)_(q_hat)
    s_1.SetLength(m1);
    // NOTE: m1 := ((m + 2)·d + d_hat      + (|idx_hid|·h + ℓr·d + d_hat)    + t) / d_hat
    //           = ((m0+2)*d0+d_hat)/d_hat + (idx_hid*h0+lr0*d0+d_hat)/d_hat + t0/d_hat
    //           =   m2ddd                 +  idxhlrddd                      + t_d
    k = 0;

    for(i=0; i<(m2ddd); i++)
    {
        s_1[k] = s[i];
        s_1[k].rep.SetLength(d_hat);
        k++;
    }

    for(i=0; i<(idxhlrddd); i++)
    {
        s_1[k] = r[i];
        s_1[k].rep.SetLength(d_hat);
        k++;
    }

    for(i=0; i<(t_d); i++)
    {
        s_1[k] = u[i];
        s_1[k].rep.SetLength(d_hat);
        k++;
    }


    // 8. coeffs_s1 ← Coeffs(s_1),   coeffs_s1 ∈ Z^(m1*d_hat)_(q_hat)
    CoeffsHat(coeffs_s1, s_1, m1);
    // NOTE: coeffs_s1 contains the same coefficients listed in w0

    // 9. Initialize rst ← 0,   rst ∈ Z, scalar
    rst     = 0;

    // 10. Initialize idx ← 0,   idx ∈ N, scalar
    idx     = 0;


    // Initialize the custom Hash function with (nonce, crs, x)
    // NOTE: using seed_crs, ipk_bytes (a1 + seed_ipk), idx_hid, instead of crs, P, C, B_f to speedup Hash_Init
    // len_seed  = SEED_LEN;                                            // uint8*    - 32 bytes
    len_a1       = calc_ser_size_poly_minbyte(d0, nbits0);              // zz_pX
    len_idx_hid  = calc_ser_size_vec_UL(num_idx_hid);                   // uint8*    - |idx_hid| bytes
    len_mex      = calc_ser_size_vec_zz_p_minbyte(c_offset, nbits0); // vec_zz_p
    len_Bounds   = calc_ser_size_vec_ZZ(2);                             // vec_ZZ (2*long) - 16 bytes
    len_aux      = 1;                                                   // uint8     - 1 byte
    // cout << "  Size Hash_Init: " << (NONCE_LEN + SEED_LEN + len_a1 + SEED_LEN + len_idx_hid + len_mex + len_Bounds + len_aux)/1024.0 << " KiB" << endl; // 1 KiB kibibyte = 1024 bytes

    lengths = {len_idx_hid, len_mex, len_Bounds, len_aux};
    max_len = *max_element(begin(lengths), end(lengths));
    buffer = new uint8_t[max_len];

    Hash_Init_To(state0, nonce, NONCE_LEN);
    Hash_Update(&state0, seed_crs, SEED_LEN);
    Hash_Update(&state0, ipk_bytes, (len_a1 + SEED_LEN));
    serialize_vec_UL(buffer, len_idx_hid, num_idx_hid, idx_hid);
    Hash_Update(&state0, buffer, len_idx_hid);
    serialize_minbyte_vec_zz_p(buffer, len_mex, c_offset, nbits0, mex);
    Hash_Update(&state0, buffer, len_mex);
    serialize_vec_ZZ(buffer, len_Bounds, 2, Bounds);
    Hash_Update(&state0, buffer, len_Bounds);
    buffer[0] = (uint8_t)(aux);
    Hash_Update(&state0, buffer, len_aux);

    delete[] buffer;
    

    // Compute the number of bytes for each component of the proof Pi
    len_valid = 1;                                                 // uint8     - 1 byte
    len_t_A = calc_ser_size_vec_poly_minbyte(n, d_hat, nbits);     // vec_zz_pX
    len_t_y = calc_ser_size_vec_poly_minbyte(n256, d_hat, nbits);  // vec_zz_pX
    len_t_g = calc_ser_size_vec_poly_minbyte(tau_ISIS, d_hat, nbits);  // vec_zz_pX
    len_w   = calc_ser_size_vec_poly_minbyte(n, d_hat, nbits);     // vec_zz_pX
    len_z_3 = calc_ser_size_vec_zz_p_minbyte(256, nbits);          // vec_zz_p
    len_h   = calc_ser_size_vec_poly_minbyte(tau_ISIS, d_hat, nbits);  // vec_zz_pX
    //len_h   = calc_ser_size_vec_poly_minbyte(tau_folded, d_hat, nbits);  // vec_zz_pX
    len_t   = calc_ser_size_poly_minbyte(d_hat, nbits);            // zz_pX
    len_f0  = calc_ser_size_poly_minbyte(d_hat, nbits);            // zz_pX
    len_z_1 = calc_ser_size_vec_poly_minbyte(m1, d_hat, nbits);    // vec_zz_pX
    len_z_2 = calc_ser_size_vec_poly_minbyte(m2, d_hat, nbits);    // vec_zz_pX

    len_Pi = len_valid + len_t_A + len_t_y + len_t_g + len_w + len_z_3 + len_h + len_t + len_f0 + len_z_1 + len_z_2;
    #ifdef VERBOSE
    cout << "  Size Pi:  " << len_Pi/1024.0 << " KiB" << endl; // 1 KiB kibibyte = 1024 bytes
    #endif

    // Allocate a vector of bytes to store the proof Pi
    *Pi_ptr = new uint8_t[len_Pi];

    #ifdef ENABLE_TIMING_PROVE
    double t2 = GetWallTime();
    #endif
    A1_s1.SetLength(n);
    b3 = 0;
    y_3.SetLength(n256);
    Pi.t_y.SetLength(n256);
    Pi.t_A.SetLength(n);
    coeffs_R_goth_mult_s1.SetLength(256);
    Pi.z_3.SetLength(256);
    for(i=0; i<n; i++)
    {
        poly_mult_hat_opt_to(A1_s1[i], crs[0][i], s_1, scratch_poly);
    }
    // 11. while (b3 == 0 ∧ idx < N) do
    while((b3 == 0) && (idx < N1))
    {
        // 12. Increment idx
        idx = idx + 1;
        // cout << "idx = " << idx << endl;

        // 13. Random generation of s_2 ∈ R^^(m2)_(q_hat)

        
        sample_s2_dense_and_packed(
            s2_raw,
            m2,
            d_hat
        );

        // 14. t_A = A_1*s_1 + A_2*s_2,  t_A ∈ R^^(n)_(q_hat)
        // for(i=0; i<n; i++)
        // {
        //     poly_mult_hat_opt_to(Pi.t_A[i], crs[1][i], s_2, scratch_poly);
        //     add(Pi.t_A[i], Pi.t_A[i], A1_s1[i]);
        // }

        for (i = 0; i < n; ++i)
        {
            ternary_poly_inner_product_to(
                Pi.t_A[i],
                crs[1][i],
                s2_raw,
                d_hat
            );

            add(Pi.t_A[i], Pi.t_A[i], A1_s1[i]);
        }

        // 15. Random generation of y_3 ∈ R^^(256/d_hat)_(q_hat)
        for(i=0; i<n256; i++)
        {
            polySampler_hat(y_3[i], s3_goth_d);
        }

        // 16. t_y = B_y*s2 + y3,  t_y ∈ R^^(256/d_hat)_(q_hat)
        // for(i=0; i<n256; i++)
        // {
        //     poly_mult_hat_opt_to(Pi.t_y[i], crs[2][i], s_2, scratch_poly);
        //     add(Pi.t_y[i], Pi.t_y[i], y_3[i] );
        // }
        for (i = 0; i < n256; ++i)
        {
            ternary_poly_inner_product_to(
                Pi.t_y[i],
                crs[2][i],
                s2_raw,
                d_hat
            );

            add(Pi.t_y[i], Pi.t_y[i], y_3[i]);
        }

        // 17. a_1 ← (t_A, t_y)
        Pi_bytes = *Pi_ptr;
        // NOTE: copy the initial status structure, already initialized with (crs, x) before row 11

        Hash_Copy_To(state, state0);

        // Initialize Pi with a flag to identify an invalid proof
        Pi.valid = 0;
        Pi_bytes[0] = 0;
        Pi_bytes += len_valid;

        // Serialize (t_A, t_y) in the proof Pi and Hash a_1 ← (t_A, t_y)
        serialize_minbyte_vec_poly_zz_pX(Pi_bytes, len_t_A, n, d_hat, nbits, Pi.t_A);
        Hash_Update(&state, Pi_bytes, len_t_A);
        Pi_bytes += len_t_A;
        serialize_minbyte_vec_poly_zz_pX(Pi_bytes, len_t_y, n256, d_hat, nbits, Pi.t_y);
        Hash_Update(&state, Pi_bytes, len_t_y);
        Pi_bytes += len_t_y;


        // 18. (R_goth_0, R_goth_1) = H(nonce, crs, x, a_1, 1)
        // 19. R_goth = R_goth_0 - R_goth_1
        #ifdef ENABLE_TIMING_PROVE
        double t__1 = GetWallTime();
        #endif
        HISIS1_optimized(R_goth, &state, m1);
        // HISIS1(R_goth_old, state, m1);
        #ifdef ENABLE_TIMING_PROVE
        double t__2 = GetWallTime();
        cout << "HISIS1: " << t__2-t__1 << endl;
        #endif
        // NOTE: R_goth ∈ {-1, 0, 1}^(256 x m_1*d_hat) ⊂ Z^(256 x m_1*d_hat)_(q_hat)
        //       equivalent to (R_goth_0 - R_goth_1) in BLNS
        // 20. coeffs_y3 ← Coeffs(y_3),   coeffs_y3 ∈ Z^(256)_(q_hat)
        CoeffsHat(coeffs_y3, y_3, n256);

        // 21.  z_3 = y_3 + R_goth*s_1,   z_3 ∈ Z^(256)_(q_hat)
        // NOTE: This equation is performed in Z not in polynomials, needing Coeffs() transformation of y_3, R_goth, and s_1
        #ifdef ENABLE_TIMING_PROVE
        double t__3 = GetWallTime();
        #endif
        for (i = 0; i < 256; i++)
        {
            ternary_sigma_dot_raw_coeffs(
                acc_coeff,
                R_goth[i],
                coeffs_s1,
                m1,
                d_hat
            );

            coeffs_R_goth_mult_s1[i] = acc_coeff;
            Pi.z_3[i] = coeffs_y3[i] + acc_coeff;
        }

        #ifdef ENABLE_TIMING_PROVE
        double t__4 = GetWallTime();
        cout << "Pi.z_3 loop: " << t__4-t__3 << endl;
        #endif

        // 22. b3 ← Rej (z_3, R_goth * s_1, s3_goth, M_3),    b3 ∈ {0, 1}
        b3 = Rej_v_zzp(Pi.z_3, coeffs_R_goth_mult_s1, q2_hat, s3_goth, M_3);

    } // End of while loop (row 11)

    #ifdef ENABLE_TIMING_PROVE
    double t3 = GetWallTime();
    #endif

    // 23. Random generation of g ∈ R^^(tau)_(q_hat)
    g.SetLength(tau_ISIS);
    #ifdef ENABLE_TIMING_PROVE
    double ta = GetWallTime();
    #endif
    for(i=0; i<tau_ISIS; i++)
    {
        g[i] = random_zz_pX(d_hat);
        // g[i][0] = 0;
        SetCoeff(g[i], 0, 0);
        // NOTE: the constant term of g[i] (x^0) must be zero
    }
    #ifdef ENABLE_TIMING_PROVE
    double tb = GetWallTime();
    cout << "loop g: " << tb-ta << endl;
    #endif
    // 24. t_g = B_g*s2 + g,  t_g ∈ R^^(tau)_(q_hat)
    Pi.t_g.SetLength(tau_ISIS);

    // for(i=0; i<tau_ISIS; i++)
    // {
    //     poly_mult_hat_opt_to(Pi.t_g[i], crs[3][i], s_2, scratch_poly);
    //     add(Pi.t_g[i], Pi.t_g[i], g[i] );
    // }

    for (i = 0; i < tau_ISIS; ++i)
    {
        ternary_poly_inner_product_to(
            Pi.t_g[i],
            crs[3][i],
            s2_raw,
            d_hat
        );

        add(Pi.t_g[i], Pi.t_g[i], g[i]);
    }

    // 25. a_2 ← (z_3, t_g)
    serialize_minbyte_vec_zz_p(Pi_bytes, len_z_3, 256, nbits, Pi.z_3);
    Hash_Update(&state, Pi_bytes, len_z_3);
    Pi_bytes += len_z_3;
    serialize_minbyte_vec_poly_zz_pX(Pi_bytes, len_t_g, tau_ISIS, d_hat, nbits, Pi.t_g);
    Hash_Update(&state, Pi_bytes, len_t_g);
    Pi_bytes += len_t_g;


    // 26. gamma ← H(nonce, crs, x, a1, a2, 2),   gamma ∈ Z^(tau_ISIS x 256+d0+3)_(q_hat)
    HISIS2(gamma, &state);
    // NOTE: gamma has 256+d0+3 columns in ISIS, while 256+d0+1 in Com

    #ifdef ENABLE_TIMING_PROVE
    double t4 = GetWallTime();
    #endif
    // Initialize h ∈ R^^(tau)_(q_hat)
    Pi.h.SetLength(tau_ISIS);
    // Precompute σ(e_j), σ(p_j), σ(β_j), σ(s), σ(r), σ(s_1)
   
    sigma_s.SetLength(m2ddd);
    sigma_r.SetLength(idxhlrddd);
    sigma_u.SetLength(t_d);
    sigma_s_1.SetLength(m1);
    
    sigma_map_opt(sigma_s, s, d_hat);
    sigma_map_opt(sigma_r, r, d_hat);
    sigma_map_opt(sigma_u, u, d_hat);
    sigma_map_opt(sigma_s_1, s_1, d_hat);
    // Precompute r_j, σ(r_j), σ(r_s,j), σ(r_r,j), σ(r_u,j), h_part1
    
    #ifdef ENABLE_TIMING_PROVE
    double t_4 = GetWallTime();
    #endif
    A_hat.SetDims(tau_ISIS, m2ddd);
    B_hat.SetDims(tau_ISIS, idxhlrddd);
    C_hat.SetDims(tau_ISIS, t_d);
    L_hat.SetDims(tau_ISIS, n256);  
    //const ulong offset_C = m2ddd+idxhlrddd;
    // Build a unique view over the A, B and C coefficient addresses.
    vector<zz_p*> abc_reps(m1);

    for (i = 0; i < tau_ISIS; ++i)
    {

        ulong p = 0;

        // reps[blk] points directly to the coefficient storage of one polynomial:
        //
        //   reps[0 .. m2ddd-1]                       -> A_hat[i][*]
        //   reps[m2ddd .. m2ddd+idxhlrddd-1]         -> B_hat[i][*]
        //   reps[m2ddd+idxhlrddd .. m1-1]            -> C_hat[i][*]

        // Initialize all polynomials in A_hat[i][*] and store raw pointers
        for (k = 0; k < m2ddd; ++k)
        {
            A_hat[i][k].SetLength(d_hat);
            abc_reps[p++] = A_hat[i][k].rep.elts();
        }

        // Initialize all polynomials in B_hat[i][*] and store raw pointers
        for (k = 0; k < idxhlrddd; ++k)
        {
            B_hat[i][k].SetLength(d_hat);
            abc_reps[p++] = B_hat[i][k].rep.elts();
        }

        // Initialize all polynomials in C_hat[i][*] and store raw pointers
        for (k = 0; k < t_d; ++k)
        {
            C_hat[i][k].SetLength(d_hat);
            abc_reps[p++] = C_hat[i][k].rep.elts();
        }

        assert(p == m1);
        
        for (j = 0; j < 256; ++j)
        {
            ternary_sigma_accumulate_gamma(
                R_goth[j],
                gamma[i][j],
                abc_reps,
                m1
            );
        }
    }

    // --------------------
    // A_hat update from P
    // Optimized loop order: j -> i -> k
    // --------------------
    for (j = 0; j < d0; ++j)
    {
        const vec_zz_p& Pj = P[j];

        for (i = 0; i < tau_ISIS; ++i)
        {
            poly_off = 0;
            const vec_zz_p& gamma_i = gamma[i];
            const zz_p& g = gamma_i[256 + j];

            for ( k = 0; k < m2ddd; ++k, poly_off += d_hat)
            {
                zz_pX& poly = A_hat[i][k];
                zz_p* rep = poly.rep.elts();

                const zz_p* src = &Pj[poly_off];

                rep[0] += g * src[0];

                t = 1;
                const zz_p* s = src + (d_hat - 1);

                for (; t + 3 < d_hat; t += 4, s -= 4)
                {
                    rep[t]     -= g * s[0];
                    rep[t + 1] -= g * s[-1];
                    rep[t + 2] -= g * s[-2];
                    rep[t + 3] -= g * s[-3];
                }

                for (; t < d_hat; ++t, --s)
                {
                    rep[t] -= g * (*s);
                }
            }
        }
    }

    for ( j = 0; j < d0; ++j)
    {
        const vec_zz_p& Cj  = C[j];

        for (i = 0; i < tau_ISIS; ++i)
        {
            const vec_zz_p& gamma_i = gamma[i];
            const zz_p& g = gamma_i[256 + j];
            poly_off = c_offset;

            // --------------------
            // B_hat update from C
            // --------------------
            for ( k = 0; k < idxhlrddd; ++k, poly_off += d_hat)
            {
                zz_pX& poly = B_hat[i][k];
                zz_p* rep = poly.rep.elts();

                const zz_p* src = &Cj[poly_off];

                rep[0] -= g * src[0];

                t = 1;
                const zz_p* s = src + (d_hat - 1);

                for (; t + 3 < d_hat; t += 4, s -= 4)
                {
                    rep[t]     += g * s[0];
                    rep[t + 1] += g * s[-1];
                    rep[t + 2] += g * s[-2];
                    rep[t + 3] += g * s[-3];
                }

                for (; t < d_hat; ++t, --s)
                {
                    rep[t] += g * (*s);
                }
            }  
        }
    }
    
    for ( j = 0; j < d0; ++j)
    {
        const vec_zz_p& Bfj = B_f[j];
        for (i = 0; i < tau_ISIS; ++i)
        {
            const vec_zz_p& gamma_i = gamma[i];
            const zz_p& g = gamma_i[256 + j];
            poly_off = 0;

            // ---------------------
            // C_hat update from B_f
            // ---------------------
            for ( k = 0; k < t_d; ++k, poly_off += d_hat)
            {
                zz_pX& poly = C_hat[i][k];
                zz_p* rep = poly.rep.elts();

                const zz_p* src = &Bfj[poly_off];

                rep[0] -= g * src[0];

                t = 1;
                const zz_p* s = src + (d_hat - 1);

                for (; t + 3 < d_hat; t += 4, s -= 4)
                {
                    rep[t]     += g * s[0];
                    rep[t + 1] += g * s[-1];
                    rep[t + 2] += g * s[-2];
                    rep[t + 3] += g * s[-3];
                }

                for (; t < d_hat; ++t, --s)
                {
                    rep[t] += g * (*s);
                }
            }
        }
    }
   
    for(i=0; i<tau_ISIS; i++)
    {
        const zz_p &m = gamma[i][256+d0+2];
        for (k = 0; k < t_d; k++)
        {
            zz_pX &poly = C_hat[i][k];

            poly.rep[0] -= m;

            for (t = 1; t < d_hat; t++)
            {
                poly.rep[t] += m;
            }
        }
    }

    for(i=0; i<tau_ISIS; i++)
    {
        poly_off = 0;
        const vec_zz_p &g_i = gamma[i];

        for (k=0; k<n256; k++, poly_off += d_hat)
        {
            zz_pX &poly = L_hat[i][k];
            poly.SetLength(d_hat);
            poly.rep[0] += g_i[poly_off];

            for(t=1; t<d_hat; t++){
                coeff_off = d_hat - t;
                poly.rep[coeff_off] -= g_i[poly_off + t];
            }
        }
    }
    

    #ifdef ENABLE_TIMING_PROVE
    double t__4 = GetWallTime();
    #endif

    // Create C_m and C_r
    // C_m.SetDims(d0, (c_offset));
    // C_r.SetDims(d0, idxhlrdd);
    // NOTE: C = [C_m C_r] ∈ Z^[d × ((ℓm+ℓr)·d+d_hat)]_(q_hat), C_m has |idx_pub|·h columns
    m_C.SetLength(d0);
    
    for (i = 0; i < d0; ++i)
    {
        InnerProduct(m_C[i], C[i], mex);
    }

    #ifdef ENABLE_TIMING_PROVE
    double t_5 = GetWallTime();
    cout << "m_C: " << t_5-t__4 << endl;
    #endif 

    poly_mult_hat_opt_to(quad_s, sigma_s, s, scratch_poly);
    poly_mult_hat_opt_to(quad_r, sigma_r, r, scratch_poly);
    poly_mult_hat_opt_to(quad_u, sigma_u, u, scratch_poly);

    // 27. for i ∈ [τ] do
    for(i=0; i<tau_ISIS; i++)
    {
        const vec_zz_p &g_i = gamma[i];

        mul(sums, Pi.z_3[0], g_i[0]);
        for(j=1; j<256; j++)
        {
            mul(product_scalar, Pi.z_3[j], g_i[j]);
            add(sums, sums, product_scalar);
            // sums += gamma[i][j] * Pi.z_3[j];
        } 

        for(j=0; j<d0; j++)
        {
            mul(product_scalar, m_C[j], g_i[256+j]);
            add(sums, sums, product_scalar);
        }

        // sums += gamma[i][256+d0]   * B_goth_s2_p;
        mul(product_scalar, B_goth_s2_p, g_i[256+d0]);
        add(sums, sums, product_scalar);

        // sums += gamma[i][256+d0+1] * B_goth_r2_p;
        mul(product_scalar, B_goth_r2_p, g_i[256+d0+1]);
        add(sums, sums, product_scalar);
         
        Pi.h[i] = g[i];
        
        mul(product_poly, quad_s, g_i[256+d0] );
        add(Pi.h[i], Pi.h[i], product_poly);

        mul(product_poly, quad_r, g_i[256+d0+1] );
        add(Pi.h[i], Pi.h[i], product_poly);

        mul(product_poly, quad_u, g_i[256+d0+2] );
        add(Pi.h[i], Pi.h[i], product_poly);
        
        poly_mult_hat_opt_to(product_poly, A_hat[i], s, scratch_poly);
        add(Pi.h[i], Pi.h[i], product_poly);
        poly_mult_hat_opt_to(product_poly, B_hat[i], r, scratch_poly);
        add(Pi.h[i], Pi.h[i], product_poly);
        poly_mult_hat_opt_to(product_poly, C_hat[i], u, scratch_poly);
        add(Pi.h[i], Pi.h[i], product_poly);
        poly_mult_hat_opt_to(product_poly, L_hat[i], y_3, scratch_poly);
        add(Pi.h[i], Pi.h[i], product_poly);

        Pi.h[i][0] -= sums;
    }

    #ifdef ENABLE_TIMING_PROVE
    double t5 = GetWallTime();
    #endif

    // 30. a_3 ← h,   a_3 ∈ R^^(τ)_(q_hat)
    serialize_minbyte_vec_poly_zz_pX(Pi_bytes, len_h, tau_ISIS, d_hat, nbits, Pi.h);
    Hash_Update(&state, Pi_bytes, len_h);
    Pi_bytes += len_h;


    // 31. μ ← H(nonce, crs, x, a1, a2, a3, 3),   μ ∈ R^^(τ)_(q_hat)
    HISIS3(mu, &state);

    A_hat_mu.SetLength(m2ddd);
    B_hat_mu.SetLength(idxhlrddd);
    C_hat_mu.SetLength(t_d);
    L_hat_mu.SetLength(n256);

    const zz_pX& mu_0 = mu[0];
    
    for (k = 0; k < m2ddd; ++k)
    {
        mul(A_hat_mu[k], mu_0, A_hat[0][k]);
    }

    for (k = 0; k < idxhlrddd; ++k)
    {
        mul(B_hat_mu[k], mu_0, B_hat[0][k]);
    }

    for (k = 0; k < t_d; ++k)
    {
        mul(C_hat_mu[k], mu_0, C_hat[0][k]);
    }

    for (k = 0; k < n256; ++k)
    {
        mul(L_hat_mu[k], mu_0, L_hat[0][k]);
    }
    
    for (i = 1; i < tau_ISIS; ++i)
    {
        const zz_pX& mu_i = mu[i];

        for (k = 0; k < m2ddd; ++k)
        {
            mul(product_poly, mu_i, A_hat[i][k]);
            add(A_hat_mu[k], A_hat_mu[k], product_poly );
        }

        for (k = 0; k < idxhlrddd; ++k)
        {
            mul(product_poly, mu_i, B_hat[i][k]);
            add(B_hat_mu[k], B_hat_mu[k], product_poly );
        }

        for (k = 0; k < t_d; ++k)
        {
            mul(product_poly, mu_i, C_hat[i][k]);
            add(C_hat_mu[k], C_hat_mu[k], product_poly );
        }

        for (k = 0; k < n256; ++k)
        {
            mul(product_poly, mu_i, L_hat[i][k]);
            add(L_hat_mu[k], L_hat_mu[k], product_poly );
        }
    }

    for (k = 0; k < m2ddd; ++k)
    {
        ModPhi_hat_q_inplace(A_hat_mu[k]);
    }

    for (k = 0; k < idxhlrddd; ++k)
    {
        ModPhi_hat_q_inplace(B_hat_mu[k]);
    }

    for (k = 0; k < t_d; ++k)
    {
        ModPhi_hat_q_inplace(C_hat_mu[k]);
    }

    for (k = 0; k < n256; ++k)
    {
        ModPhi_hat_q_inplace(L_hat_mu[k]);
    }

    #ifdef ENABLE_TIMING_PROVE
    double t6 = GetWallTime();
    #endif

    // 32. B   ← [B_y; B_g],   B ∈ R^^((256/d_hat + tau) x m2)_(q_hat)
    // 33. δ_1 ← Sum_(i=1,τ){ μ_i · γ_(i,256+d+1) },   δ_1 ∈ R^^_(q_hat)
    // 34. δ_2 ← Sum_(i=1,τ){ μ_i · γ_(i,256+d+2) },   δ_2 ∈ R^^_(q_hat)
    // 35. δ_3 ← Sum_(i=1,τ){ μ_i · γ_(i,256+d+3) },   δ_3 ∈ R^^_(q_hat)
    // 37.  (r_s,j , r_r,j , r_u,j ) ← r_j,
    //       r_s,j ∈ R^^(((m+2)d+d_hat)/d_hat)_(q_hat)
    //       r_r,j ∈ R^^((|idx_hid|·h+ℓr·d+d_hat)/d_hat)_(q_hat)
    //       r_u,j ∈ R^^(t/d_hat)_(q_hat)
    //       c_r,j is the poly. vector with coeff. the j-th row of C_r
    // NOTE: σ(r_s,j), σ(r_r,j), σ(r_u,j), σ(c_r,j) already pre-computed
    // 38. Construction of d_1 ∈ R^^(2*m1+2(256/d_hat+τ))_(q_hat)
    // NOTE: save the pointer to the bytes already written in Pi, i.e. (t_A, t_y, z_3, t_g, h)
    Pi_bytes0 = Pi_bytes;

    // NOTE: save the current status structure of the Hash function, already updated in previous steps
    Hash_Copy_To(state0, state);

    #ifdef ENABLE_TIMING_PROVE
    double t8 = GetWallTime();
    #endif
    // 39. while (rst == 0 ∧ idx < N) do
    s3y0.SetLength(d_hat);
    s4y1.SetLength(d_hat);
    s5y2.SetLength(d_hat);
    y3s0.SetLength(d_hat);
    y4s1.SetLength(d_hat);
    y5s2.SetLength(d_hat);
    acc.SetLength(d_hat);

    const vec_zz_p& g0 = gamma[0];

    mul(delta_1, mu[0], g0[256 + d0]);
    mul(delta_2, mu[0], g0[256 + d0 + 1]);
    mul(delta_3, mu[0], g0[256 + d0 + 2]);

    for (i = 1; i < tau_ISIS; ++i)
    {
        const vec_zz_p& g_i = gamma[i];

        mul(product_poly, mu[i], g_i[256 + d0]);
        add(delta_1, delta_1, product_poly);

        mul(product_poly, mu[i], g_i[256 + d0 + 1]);
        add(delta_2, delta_2, product_poly);

        mul(product_poly, mu[i], g_i[256 + d0 + 2]);
        add(delta_3, delta_3, product_poly);
    }

    ternary_poly_inner_product_to(
        b_s2,
        crs[4][0],
        s2_raw,
        d_hat
    );

    y_1.SetLength(m1);
    y_2.SetLength(m2);
    y.SetLength( n256 + tau_ISIS );
    Pi.w.SetLength(n);
    Pi.z_2.SetLength(m2);
    c_s2.SetLength(m2);
    Pi.z_1.SetLength(m1);
    c_s1.SetLength(m1);
    sigma_y_1.SetLength(m1);

    for(j=0; j < m1; j++ )
    {
        sigma_y_1[j].SetLength(d_hat);
    }

    while((rst == 0) && (idx < N1))
    {
        // NOTE: restore the pointer to Pi and the status structure of the Hash function
        Pi_bytes = Pi_bytes0;

        Hash_Copy_To(state, state0);

        b1 = 0; b2 = 0;

        // 40. Increment idx
        idx = idx + 1;
        // cout << "idx = " << idx << endl;


        // 41.1 Random generation of y_1 ∈ R^^m1_(q_hat)
        for(i=0; i<m1; i++)
        {
            polySampler_hat(y_1[i], s1_goth_d);
        }

        // 41.2 Random generation of y_2 ∈ R^^m2_(q_hat)
        for(i=0; i<m2; i++)
        {
            polySampler_hat(y_2[i], s2_goth_d);
        }

        // 42. y ← (y1; σ(y1); −B*y2; σ(-B*y2)),     y ∈ R^^(2*m1 + 2*(256/d_hat + tau))_(q_hat)
        sigma_map_opt_no_alloc(sigma_y_1, y_1, d_hat);

        // Compute -B*y2
        for (i = 0; i < n256; i++)
        {
            poly_mult_hat_opt_to(y[i], crs[2][i], y_2, scratch_poly);
            y[i] = -y[i];
        }
        
        for (i = 0; i < tau_ISIS; i++)
        {
            poly_mult_hat_opt_to(y[n256 + i], crs[3][i], y_2, scratch_poly);
            y[n256 + i] = -y[n256 + i];
        }
    
        // 43. w = A1*y1 + A2*y2,  w ∈ R^^(n)_(q_hat)
        for (i = 0; i < n; ++i)
        {
        
            poly_mult_hat_opt_to(product_poly, crs[0][i], y_1, scratch_poly);
            poly_mult_hat_opt_to(Pi.w[i], crs[1][i], y_2, scratch_poly);
            add(Pi.w[i], Pi.w[i], product_poly);
        }

        // -----------------------------------------------------------------------------
        // Compute all mixed and quadratic products.
        // (needed by both f1 and f0)
        // -----------------------------------------------------------------------------

        mul(s3y0, y_1[0], sigma_s_1[0]);
        mul(y3s0, sigma_y_1[0], s_1[0]);
        mul(y3y0, y_1[0], sigma_y_1[0]);

        mul(s4y1, y_1[m2ddd], sigma_s_1[m2ddd]);
        mul(y4s1, sigma_y_1[m2ddd], s_1[m2ddd]);
        mul(y4y1, y_1[m2ddd], sigma_y_1[m2ddd]);

        mul(s5y2, y_1[t_d_offset], sigma_s_1[t_d_offset]);
        mul(y5s2, sigma_y_1[t_d_offset], s_1[t_d_offset]);
        mul(y5y2, y_1[t_d_offset], sigma_y_1[t_d_offset]);

        for (k = 1; k < m2ddd; ++k)
        {
            // s3y0 = y_s^T * sigma(s)
            mul(product_poly, y_1[k], sigma_s_1[k]);
            add(s3y0, s3y0, product_poly);

            // y3s0 = sigma(y_s)^T * s
            mul(product_poly, sigma_y_1[k], s_1[k]);
            add(y3s0, y3s0, product_poly);

            // y3y0 = y_s^T * sigma(y_s)
            mul(product_poly, y_1[k], sigma_y_1[k]);
            add(y3y0, y3y0, product_poly);
        }

        for (k = m2ddd + 1; k < m2ddd + idxhlrddd; ++k)
        {
            mul(product_poly, y_1[k], sigma_s_1[k]);
            add(s4y1, s4y1, product_poly);

            mul(product_poly, sigma_y_1[k], s_1[k]);
            add(y4s1, y4s1, product_poly);

            mul(product_poly, y_1[k], sigma_y_1[k]);
            add(y4y1, y4y1, product_poly);
        }

        for (k = m2ddd + idxhlrddd + 1; k < m1; ++k)
        {
            mul(product_poly, y_1[k], sigma_s_1[k]);
            add(s5y2, s5y2, product_poly);

            mul(product_poly, sigma_y_1[k], s_1[k]);
            add(y5s2, y5s2, product_poly);

            mul(product_poly, y_1[k], sigma_y_1[k]);
            add(y5y2, y5y2, product_poly);
        }

        // One reduction per accumulator
        ModPhi_hat_q_inplace(s3y0);
        ModPhi_hat_q_inplace(y3s0);
        ModPhi_hat_q_inplace(y3y0);

        ModPhi_hat_q_inplace(s4y1);
        ModPhi_hat_q_inplace(y4s1);
        ModPhi_hat_q_inplace(y4y1);

        ModPhi_hat_q_inplace(s5y2);
        ModPhi_hat_q_inplace(y5s2);
        ModPhi_hat_q_inplace(y5y2);

        // -----------------------------------------------------------------------------
        // Compute acc
        // -----------------------------------------------------------------------------

        
        mul(acc, y_1[0], A_hat_mu[0]);

        for (k = 1; k < m2ddd; ++k)
        {
            mul(product_poly, y_1[k], A_hat_mu[k]);
            add(acc, acc, product_poly);
        }

        for (k = 0; k < idxhlrddd; ++k)
        {
            mul(product_poly, y_1[m2ddd + k], B_hat_mu[k]);
            add(acc, acc, product_poly);
        }

        for (k = 0; k < t_d; ++k)
        {
            mul( product_poly,y_1[m2ddd + idxhlrddd + k],C_hat_mu[k]);
            add(acc, acc, product_poly);
        }

        for (k = 0; k < n256; ++k)
        {
            mul(product_poly, y[k], L_hat_mu[k]);
            add(acc, acc, product_poly);
        }

        ModPhi_hat_q_inplace(acc);

        // -----------------------------------------------------------------------------
        // Compute f1
        // -----------------------------------------------------------------------------

        f1 = acc;
        // f1 += delta_1 * (s3y0 + y3s0)
        add(acc, s3y0, y3s0);
        mul(product_poly, delta_1, acc);
        add(f1, f1, product_poly);
        // f1 += delta_2 * (s4y1 + y4s1)
        add(acc, s4y1, y4s1);
        mul(product_poly, delta_2, acc);
        add(f1, f1, product_poly);
        // f1 += delta_3 * (s5y2 + y5s2)
        add(acc, s5y2, y5s2);
        mul(product_poly, delta_3, acc);
        add(f1, f1, product_poly);
        ModPhi_hat_q_inplace(f1);

        // Accumulate sum_i mu[i] * y[n256+i], then reduce once
        mul(mu_y_acc, mu[0], y[n256]);
        for (i = 1; i < tau_ISIS; ++i)
        {
            mul(product_poly, mu[i], y[n256 + i]);
            add(mu_y_acc, mu_y_acc, product_poly);
        }

        ModPhi_hat_q_inplace(mu_y_acc);
        add(f1, f1, mu_y_acc);


        // 45. t = b*s2 + f1
        Pi.t = b_s2;
        add(Pi.t, Pi.t, f1);

        // -----------------------------------------------------------------------------
        // Compute f0
        // -----------------------------------------------------------------------------

        poly_mult_hat_opt_to(Pi.f0, crs[4][0], y_2, product_poly);

        
        mul(product_poly, delta_1, y3y0);
        add(Pi.f0, Pi.f0, product_poly);
        mul(product_poly, delta_2, y4y1);
        add(Pi.f0, Pi.f0, product_poly);
        mul(product_poly, delta_3, y5y2);
        add(Pi.f0, Pi.f0, product_poly);
        ModPhi_hat_q_inplace(Pi.f0);
        
        // NOTE: D2_y = (D2_2_1 * y_1) was already computed in row 44 (1st addend of f1)

        // 47. a_4 ← (t, w, f0)
        serialize_minbyte_poly_zz_pX(Pi_bytes, len_t, d_hat, nbits, Pi.t);
        Hash_Update(&state, Pi_bytes, len_t);
        Pi_bytes += len_t;
        serialize_minbyte_vec_poly_zz_pX(Pi_bytes, len_w, n, d_hat, nbits, Pi.w);
        Hash_Update(&state, Pi_bytes, len_w);
        Pi_bytes += len_w;
        serialize_minbyte_poly_zz_pX(Pi_bytes, len_f0, d_hat, nbits, Pi.f0);
        Hash_Update(&state, Pi_bytes, len_f0);
        Pi_bytes += len_f0;

        // 48. c ← H(nonce, crs, x, a1, a2, a3, a4, 4),   c ∈ C ⊂ R^_(q_hat)
        HISIS4(c, &state);

        // 49. for i ∈ {1, 2} do
        // NOTE: for simplicity, next operations are duplicated with suffixes _1 and _2
        // 50. z_i ← y_i + c*s_i,   z_i ∈ R^^(m_i)_(q_hat)
    

        for(i=0; i<m1; i++)
        {
            mul(c_s1[i], c, s_1[i]);
            ModPhi_hat_q_inplace(c_s1[i]);
            add(Pi.z_1[i], c_s1[i] , y_1[i] );
        }

        // 51. b_i ← Rej(z_i, c*s_i, s_i_goth, M_i),   b_i ∈ {0, 1}
        b1 = Rej_v_zzpX(Pi.z_1, c_s1, q2_hat, s1_goth, M_1);
        
        // NOTE: if b1 == 0, continue the while loop
        if (b1 == 0)
        {
            rst = 0;
            continue;
        }

        for (i = 0; i < m2; ++i)
        {
            ternary_poly_mul_to(
                c_s2[i],
                c,
                s2_raw,
                static_cast<long>(i),
                d_hat
            );

            add(Pi.z_2[i], c_s2[i], y_2[i]);
        }

        b2 = Rej_v_zzpX(Pi.z_2, c_s2, q2_hat, s2_goth, M_2);

        // 52. rst ← b1*b2
        rst = b1*b2;

    } // End of while loop (row 39)


    #ifdef ENABLE_TIMING_PROVE
    double t9 = GetWallTime();
    #endif


    // 53. if rst = 1 then
    if (rst == 1)
    {
        // 54. π ← (t_A, t_y, z_3, t_g, h, t, w, f0, z_1, z_2)
        // NOTE:   (t_A, t_y, z_3, t_g, h, t, w, f0) already serialized in Pi_bytes

        // Serialize z_1, z_2 in bytes at the end of the proof Pi
        serialize_minbyte_vec_poly_zz_pX(Pi_bytes, len_z_1, m1, d_hat, nbits, Pi.z_1);
        Pi_bytes += len_z_1;
        serialize_minbyte_vec_poly_zz_pX(Pi_bytes, len_z_2, m2, d_hat, nbits, Pi.z_2);
        // Pi_bytes += len_z_2;

        // NOTE: additional flag, to identify a valid proof Pi
        Pi.valid = 1;
        (*Pi_ptr)[0] = 1;

        idx_ISIS = idx;
        // cout << "idx_ISIS = " << idx_ISIS << endl;

        // 55. return π
    }

    #ifdef ENABLE_TIMING_PROVE
    double t10 = GetWallTime();
    cout << "init: " << t2-t1 << endl;
    cout << "first while: " << t3-t2 << endl;
    cout << "g and gamma: " << t4-t3 << endl;
    cout << "setDims+sigmamap: " << t_4-t4 << endl;
    cout << "precomputing: " << t__4-t_4 << endl;
    cout << "h computation: " << t5-t_5 << endl;
    cout << "challenge mu_i: " << t6-t5 << endl;
    cout << "B: " << t8-t6 << endl;
    cout << "second while: " << t9-t8 << endl;
    cout << "proof: " << t10-t9 << endl;
    #endif
    // 56. else return ⊥
    // NOTE: invalid proof, with Pi.valid = 0
}

//==============================================================================
// Verify_ISIS  -   Verify the Commitment (Verify^HISIS_ISIS).
//                  This function takes as input crs, x, and the proof π.
//                  It returns as output “reject” or “accept”.
//
// Inputs:
// - nonce:         random cryptographic nonce (challenge) generated by Verifier
// -  seed_crs:     initial public seed for crs structure
// -  crs:          structure crs_ISIS, generated by Hcrs from seed_crs
// -  ipk_bytes:    serialized Issuer Public Key
// - (P, C, mex, B_f,
//    Bounds, aux): they correspond to x
// -  Pi_ptr:       pointer to proof (π) data
// -  idx_hid:      indexes of undisclosed attributes (hidden)
//
// Output:
// -  0 or 1:       reject or accept
//==============================================================================
long Verify_ISIS(const uint8_t* nonce, const uint8_t* seed_crs, const CRS_t& crs, const uint8_t* ipk_bytes, const mat_zz_p& P, const mat_zz_p& C, const vec_zz_p& mex, const mat_zz_p& B_f, const vec_ZZ& Bounds, const long& aux, uint8_t** Pi_ptr, const vec_UL &idx_hid)
{
    // NOTE: assuming that current modulus is q2_hat (not q0)

    ulong           poly_off, t, i, j, k;
    Mat<zz_pX>      B, A_hat, B_hat, C_hat, L_hat;
    vec_zz_pX       z;
    vec_zz_pX       mu;
    zz_pX           tmp_sub;
    // zz_p            s;
    // vec_zz_pX       tmp_vec, t_B, r_j, p_j, Beta_j, acc_vec, coeffs_ones, sigma_ones;
    // vec_zz_p        ones, e_tmp;
    // Mat<zz_pX>      e_, sigma_e_, sigma_p_, sigma_Beta_, sigma_c_r_;
    // Mat<zz_pX>      B, sigma_r_, sigma_r_s_, sigma_r_r_, sigma_r_u_;
    // mat_zz_p        C_r;
    // mat_zz_p        R_goth, C_m;
    zz_pX           sigma_tmp, delta_1, delta_2, delta_3, product1 , product2, scratch_poly, acc, acc2, c, d_0, sum, z3z0, z4z1, z5z2;
    mat_zz_p        gamma;
    vec_zz_p        m_C;
    ZZ              B_goth_s2, B_goth_r2, B_goth2;
    zz_p            B_goth_s2_p, B_goth_r2_p, sums;
    ZZ              norm2_z1, norm2_z2, norm2_z3;
    HASH_STATE_t    state;
    size_t          coeff_off, len_a1, len_idx_hid, len_mex, len_Bounds, len_aux, max_len;
    size_t          len_t_A, len_t_y, len_t_g, len_w, len_z_3, len_h;
    size_t          len_t, len_f0, len_z_1, len_z_2, len_valid, len_in; //len_Pi;
    uint8_t        *buffer, *Pi_bytes;
    vector<size_t>  lengths;
    PROOF_I_t       Pi;
    // Initialise constants
    const ulong     num_idx_hid = idx_hid.length(); // number of undisclosed attributes (hidden)
    const ulong     num_idx_pub = l0 - num_idx_hid; // number of disclosed attributes (revealed)
    const ulong     n           = n_ISIS;
    const ulong     m1          = (((m0+2)*d0 + (num_idx_hid*h0 + lr0*d0) + t0 + 2*d_hat) / d_hat); // m_1 for Π^ISIS_NIZK
    const ulong     m2          = m2_ISIS;                                                          // m_2 for Π^ISIS_NIZK
    const ulong     m2ddd       = ((m0 + 2)*d0 + d_hat)/d_hat;              // ((m+2)·d + d^)/d^
    const ulong     idxhlrdd    = (num_idx_hid * h0) + (lr0 * d0) + d_hat;  // |idx_hid|·h + ℓr·d + d^
    const ulong     idxhlrddd   = idxhlrdd/d_hat;
    const ulong     n256        = (256/d_hat);
    const ulong     t_d         = (t0/d_hat);
    const ulong     c_offset    = num_idx_pub * h0;
    //const ulong     m1_n256_tau = 2*m1 + (n256 + tau_ISIS);
    const int       nbits0      = ceil(log2(conv<double>(q0-1)));
    const int       nbits       = ceil(log2(conv<double>(q2_hat-1)));
    scratch_poly.SetLength(d_hat);
    // Initialise the "goth" constants
    // NOTE: all values are squared, to avoid sqrt and floating points
    // (B_goth_s^2, B_goth_r^2) ← Bounds,   (B_goth_s^2, B_goth_r^2) ∈ Z^2
    B_goth_s2 = Bounds[0];
    B_goth_r2 = Bounds[1];

    // Square of B_goth = sqrt(B_goth_s^2 + B_goth_r^2 + t0)
    B_goth2 = B_goth_s2 + B_goth_r2 + t0;

    B_goth_s2_p = conv<zz_p>(B_goth_s2);
    B_goth_r2_p = conv<zz_p>(B_goth_r2);

    // s1_goth = alpha_1*nu0*B_goth
    // s2_goth = alpha_2*nu0*sqrt(m2*d_hat)
    // s3_goth = alpha_3*w_max(lambda0)*B_goth
    const ZZ  s1_goth2  = sqr(ZZ(alpha_1)  * ZZ(nu0))   * B_goth2;
    const ZZ  s2_goth2  = sqr(ZZ(alpha_2)  * ZZ(nu0))   * ( m2 * ZZ(d_hat) );
    const ZZ  s3_goth2  = sqr(ZZ(alpha_3)) * ZZ(w_max2) * B_goth2;
    const ZZ  B_goth2_1 = s1_goth2 * ( 2*m1*ZZ(d_hat) );
    const ZZ  B_goth2_2 = s2_goth2 * ( 2*m2*ZZ(d_hat) );
    const ZZ  B_goth2_3 = RoundToZZ( sqr(RR(1.7)) * conv<RR>(s3_goth2) * RR(256) );
    // NOTE:  B_goth2_3 is a floating point (due to 1.7 factor), rounded to nearest integer

    //t2-t1 TIME

    // 1. Retrieve (A_1, A_2, B_y, B_g, b) ← crs_ISIS
    // A_1     = crs[0];    // ∈ R^^(n x m1)_(q_hat)
    // A_2     = crs[1];    // ∈ R^^(n x m2)_(q_hat)
    // B_y     = crs[2];    // ∈ R^^(256/d^ x m2)_(q_hat)
    // B_g     = crs[3];    // ∈ R^^(tau_ISIS x m2)_(q_hat)
    // b       = crs[4][0]; // ∈ R^^(m2)_(q_hat)         NOTE: b in crs is a (1 x m_2) matrix

    // 2. (P, C, mex, B_f, Bounds, aux) ← x
    // NOTE: directly provided as inputs
    #ifdef ENABLE_TIMING_VERIFY
    double t1 = GetWallTime();
    #endif
    // Initialize the custom Hash function with (nonce, crs, x)
    // NOTE: using seed_crs, ipk_bytes (a1 + seed_ipk), idx_hid, instead of crs, P, C, B_f to speedup Hash_Init
    // len_seed  = SEED_LEN;                                            // uint8*    - 32 bytes
    len_a1       = calc_ser_size_poly_minbyte(d0, nbits0);              // zz_pX
    len_idx_hid  = calc_ser_size_vec_UL(num_idx_hid);                   // uint8*    - |idx_hid| bytes
    len_mex      = calc_ser_size_vec_zz_p_minbyte(c_offset, nbits0); // vec_zz_p
    len_Bounds   = calc_ser_size_vec_ZZ(2);                             // vec_ZZ (2*long) - 16 bytes
    len_aux      = 1;                                                   // uint8     - 1 byte
    // cout << "  Size Hash_Init: " << (NONCE_LEN + SEED_LEN + len_a1 + SEED_LEN + len_idx_hid + len_mex + len_Bounds + len_aux)/1024.0 << " KiB" << endl; // 1 KiB kibibyte = 1024 bytes

    lengths = {len_idx_hid, len_mex, len_Bounds, len_aux};
    max_len = *max_element(begin(lengths), end(lengths));
    buffer = new uint8_t[max_len];

    Hash_Init_To(state, nonce, NONCE_LEN);
    Hash_Update(&state, seed_crs, SEED_LEN);
    Hash_Update(&state, ipk_bytes, (len_a1 + SEED_LEN));
    serialize_vec_UL(buffer, len_idx_hid, num_idx_hid, idx_hid);
    Hash_Update(&state, buffer, len_idx_hid);
    serialize_minbyte_vec_zz_p(buffer, len_mex, c_offset, nbits0, mex);
    Hash_Update(&state, buffer, len_mex);
    serialize_vec_ZZ(buffer, len_Bounds, 2, Bounds);
    Hash_Update(&state, buffer, len_Bounds);
    buffer[0] = (uint8_t)(aux);
    Hash_Update(&state, buffer, len_aux);

    delete[] buffer;

    // 3. P ← [P0,  0_(d × d_hat)],   P ∈ Z^[d × (m+2)·d + d_hat]_(q_hat)
    // NOTE: zero padding of P already done in V_Verify

    // 4. C ← [C0,  0_(d × d_hat)],   C ∈ Z^[d × ((ℓm+ℓr)·d + d_hat)]_(q_hat)
    // NOTE: zero padding of C already done in V_Verify


    // 5. (t_A, t_y, z_3, t_g, h, t, w, f0, z_1, z_2) ← π
    #ifdef ENABLE_TIMING_VERIFY
    double t2 = GetWallTime();
    #endif
    // Compute the number of bytes for each component of the proof Pi
    len_valid = 1;                                                 // uint8     - 1 byte
    len_t_A = calc_ser_size_vec_poly_minbyte(n, d_hat, nbits);     // vec_zz_pX
    len_t_y = calc_ser_size_vec_poly_minbyte(n256, d_hat, nbits);  // vec_zz_pX
    len_t_g = calc_ser_size_vec_poly_minbyte(tau_ISIS, d_hat, nbits);  // vec_zz_pX
    len_w   = calc_ser_size_vec_poly_minbyte(n, d_hat, nbits);     // vec_zz_pX
    len_z_3 = calc_ser_size_vec_zz_p_minbyte(256, nbits);
    len_h   = calc_ser_size_vec_poly_minbyte(tau_ISIS, d_hat, nbits);  // vec_zz_pX          // vec_zz_p
    //len_h   = calc_ser_size_vec_poly_minbyte(tau_ISIS/2, d_hat, nbits);  // vec_zz_pX
    len_t   = calc_ser_size_poly_minbyte(d_hat, nbits);            // zz_pX
    len_f0  = calc_ser_size_poly_minbyte(d_hat, nbits);            // zz_pX
    len_z_1 = calc_ser_size_vec_poly_minbyte(m1, d_hat, nbits);    // vec_zz_pX
    len_z_2 = calc_ser_size_vec_poly_minbyte(m2, d_hat, nbits);    // vec_zz_pX

    // len_Pi = len_valid + len_t_A + len_t_y + len_t_g + len_w + len_z_3 + len_h + len_t + len_f0 + len_z_1 + len_z_2;
    // cout << "  Size Pi:  " << len_Pi/1024.0 << " KiB" << endl; // 1 KiB kibibyte = 1024 bytes

    // Deserialize the proof Pi
    Pi_bytes = *Pi_ptr;
    Pi.valid = (long)(Pi_bytes[0]);
    Pi_bytes += len_valid;

    // Check if Pi contains a valid proof
    if (Pi.valid != 1)
    {
        cout << "ERROR! Pi does not contain a valid proof" << endl;
        return 0;
    }
    #ifdef ENABLE_TIMING_VERIFY
    double t3 = GetWallTime();
    #endif
    deserialize_minbyte_vec_poly_zz_pX(Pi.t_A, n, d_hat, nbits, Pi_bytes, len_t_A);
    Pi_bytes += len_t_A;
    deserialize_minbyte_vec_poly_zz_pX(Pi.t_y, n256, d_hat, nbits, Pi_bytes, len_t_y);
    Pi_bytes += len_t_y;
    deserialize_minbyte_vec_zz_p(Pi.z_3, 256, nbits, Pi_bytes, len_z_3);
    Pi_bytes += len_z_3;
    deserialize_minbyte_vec_poly_zz_pX(Pi.t_g, tau_ISIS, d_hat, nbits, Pi_bytes, len_t_g);
    Pi_bytes += len_t_g;
    deserialize_minbyte_vec_poly_zz_pX(Pi.h, tau_ISIS, d_hat, nbits, Pi_bytes, len_h);
    Pi_bytes += len_h;
    deserialize_minbyte_poly_zz_pX(Pi.t, d_hat, nbits, Pi_bytes, len_t);
    Pi_bytes += len_t;
    deserialize_minbyte_vec_poly_zz_pX(Pi.w, n, d_hat, nbits, Pi_bytes, len_w);
    Pi_bytes += len_w;
    deserialize_minbyte_poly_zz_pX(Pi.f0, d_hat, nbits, Pi_bytes, len_f0);
    Pi_bytes += len_f0;
    deserialize_minbyte_vec_poly_zz_pX(Pi.z_1, m1, d_hat, nbits, Pi_bytes, len_z_1);
    Pi_bytes += len_z_1;
    deserialize_minbyte_vec_poly_zz_pX(Pi.z_2, m2, d_hat, nbits, Pi_bytes, len_z_2);
    // Pi_bytes += len_z_2;

    // t3-t2 TIME
    #ifdef ENABLE_TIMING_VERIFY
    double t4 = GetWallTime();
    #endif
    // 6. a_1 ← (t_A, t_y)
    Pi_bytes = *Pi_ptr + len_valid;
    len_in = len_t_A + len_t_y;
    Hash_Update(&state, Pi_bytes, len_in);
    Pi_bytes += len_in;
    #ifdef ENABLE_TIMING_VERIFY
    double t5 = GetWallTime();
    cout << "init 1 " << t2-t1 << endl;
    cout << "init 2 " << t3-t2 << endl;
    cout << "init 3 " << t4-t3 << endl;
    cout << "hash update " << t5-t4 << endl;
    #endif

    // 7. a2 ← (z_3, t_g)
    // 8. a3 ← h
    // 9. a4 ← (t, w, f0)
    // 10. (R_goth_0, R_goth_1) = H(nonce, crs, x, a_1, 1)
    // 11. R_goth = R_goth_0 - R_goth_1

    #ifdef ENABLE_TIMING_VERIFY
    double tHISIS1_i = GetWallTime();
    #endif
    std::vector<TernaryCoeffStructure> R_goth(256);
    HISIS1_optimized(R_goth, &state, m1);
    #ifdef ENABLE_TIMING_VERIFY
    double tHISIS1_e = GetWallTime();
    cout << "HISIS1 new: " << tHISIS1_e-tHISIS1_i << endl;
    #endif
    
    #ifdef ENABLE_TIMING_VERIFY
    double thashupdt_i = GetWallTime();
    #endif
    len_in = len_z_3 + len_t_g;
    Hash_Update(&state, Pi_bytes, len_in);
    #ifdef ENABLE_TIMING_VERIFY
    double thashupdt_e = GetWallTime();
    cout << "hashupdt: " << thashupdt_e-thashupdt_i << endl;
    #endif
    Pi_bytes += len_in;
    #ifdef ENABLE_TIMING_VERIFY
    double tHISIS2_i = GetWallTime();
    #endif
    HISIS2(gamma, &state);
    #ifdef ENABLE_TIMING_VERIFY
    double tHISIS2_e = GetWallTime();
    cout << "HISIS2: " << tHISIS2_e-tHISIS2_i << endl;
    #endif
    // NOTE: gamma has 256+d0+3 columns in ISIS, while 256+d0+1 in Com

    // 13. μ ← H(nonce, crs, x, a1, a2, a3, 3),   μ ∈ R^^(τ)_(q_hat)
    #ifdef ENABLE_TIMING_VERIFY
    double thashupdt2_i = GetWallTime();
    #endif
    Hash_Update(&state, Pi_bytes, len_h);
    #ifdef ENABLE_TIMING_VERIFY
    double thashupdt2_e = GetWallTime();
    cout << "hashupdt2: " << thashupdt2_e-thashupdt2_i << endl;
    #endif

    #ifdef ENABLE_TIMING_VERIFY
    double tHISIS3_i = GetWallTime();
    #endif
    Pi_bytes += len_h;
    HISIS3(mu, &state);
    #ifdef ENABLE_TIMING_VERIFY
    double tHISIS3_e = GetWallTime();
    cout << "HISIS3: " << tHISIS3_e-tHISIS3_i << endl;
    #endif

    // 14. c ← H(nonce, crs, x, a1, a2, a3, a4, 4),   c ∈ C ⊂ R^_(q_hat)
    len_in = len_t + len_w + len_f0;
    #ifdef ENABLE_TIMING_VERIFY
    double thashupdt3_i = GetWallTime();
    #endif
    Hash_Update(&state, Pi_bytes, len_in);
    #ifdef ENABLE_TIMING_VERIFY
    double thashupdt3_e = GetWallTime();
    cout << "hashupdt3: " << thashupdt3_e-thashupdt3_i << endl;
    #endif

    // Pi_bytes += len_in;
    #ifdef ENABLE_TIMING_VERIFY
    double tHISIS4_i = GetWallTime();
    #endif
    HISIS4(c, &state);
    #ifdef ENABLE_TIMING_VERIFY
    double tHISIS4_e = GetWallTime();
    cout << "HISIS4: " << tHISIS4_e-tHISIS4_i << endl;
    #endif

    #ifdef ENABLE_TIMING_VERIFY
    double t6 = GetWallTime();
    cout << "hash update" << t2-t1 << endl;
    cout << "calc ser" << t3-t2 << endl;
    cout << "deserialize" << t4-t3 << endl;
    cout << "All HISIS" << t6-t5 << endl;
        //t4-t3 TIME
    double t_1 = GetWallTime();
    #endif
    //15. z ←  (z[0]    z[1]     z[2]  z[3]     z[4]    z[5]  z[6]    z[7]    z[8]    z[9])           z ∈ R^^(2*m1 + 2*(256/d_hat + tau))_(q_hat)
    //          m2ddd, idxhlrddd, t_d, m2ddd, idxhlrddd, t_d, n256,  tau_ISIS,  n256, tau_ISIS
    //           m1          |           m1                 | n256 | tau_ISIS | n256| tau_ISIS
    // We actually fill z with just z[6] and z[7], since :
    // z_1 = ( z[0] z[1] z[2] ) is taken from π (line 5.)
    // σ(z_1) = ( z[3] z[4] z[5] ) we compute it on the fly where is needed (line 21.4)
    // z[8] and z[9] are not needed for any computation.

    // Actual z size: z ∈ R^^(256/d_hat + tau)_(q_hat)
    z.SetLength( n256 + tau_ISIS );  

    // z {from 0 to n256} ← z[6] 
    for(i=0; i<n256; i++)
    {
        mul(product1, c, Pi.t_y[i]);
        ModPhi_hat_q_inplace(product1);
        poly_mult_hat_opt_to(product2, crs[2][i], Pi.z_2, scratch_poly);
        sub(z[i], product1, product2 );
        
    }
    // z {from n256 to n256 + tau_ISIS} ← z[7] 
    for(i=n256; i<(n256 + tau_ISIS); i++)
    {
        mul(product1, c, Pi.t_g[i-n256]);
        ModPhi_hat_q_inplace(product1);
        poly_mult_hat_opt_to(product2, crs[3][i-n256], Pi.z_2, scratch_poly);
        sub(z[i], product1, product2);
    }
    #ifdef ENABLE_TIMING_VERIFY
    double t_2 = GetWallTime();
    cout << "z[]" << t_2-t_1 << endl;
    #endif

    // Create C_m, C_r is not precomputed
    #ifdef ENABLE_TIMING_VERIFY
    double tCm_1 = GetWallTime();
    #endif
    m_C.SetLength(d0);

    for (i = 0; i < d0; ++i)
    {
        InnerProduct(m_C[i], C[i], mex);
    }
   
    #ifdef ENABLE_TIMING_VERIFY
    double tCm_2 = GetWallTime();
    cout << "Cm: " << tCm_2-tCm_1 << endl;
    #endif

    // 16. Construction of A^ ∈ R^^(τ × ((m+2)d+d_hat)/d_hat)_(q_hat)
    // 17. Construction of B^ ∈ R^^((|idx_hid|·h+ℓr·d+d_hat)/d_hat)_(q_hat)
    // 18. Construction of C^ ∈ R^^(t/d_hat)_(q_hat)
    #ifdef ENABLE_TIMING_VERIFY
    double tA_1 = GetWallTime();
    #endif
    
    A_hat.SetDims(tau_ISIS, m2ddd);
    B_hat.SetDims(tau_ISIS, idxhlrddd);
    C_hat.SetDims(tau_ISIS, t_d);  

    // Build a unique view over the A, B and C coefficient addresses.
    vector<zz_p*> abc_reps(m1);

    for (i = 0; i < tau_ISIS; ++i)
    {

        ulong p = 0;

        // reps[blk] points directly to the coefficient storage of one polynomial:
        //
        //   reps[0 .. m2ddd-1]                       -> A_hat[i][*]
        //   reps[m2ddd .. m2ddd+idxhlrddd-1]         -> B_hat[i][*]
        //   reps[m2ddd+idxhlrddd .. m1-1]            -> C_hat[i][*]

        // Initialize all polynomials in A_hat[i][*] and store raw pointers
        for (k = 0; k < m2ddd; ++k)
        {
            A_hat[i][k].SetLength(d_hat);
            abc_reps[p++] = A_hat[i][k].rep.elts();
        }

        // Initialize all polynomials in B_hat[i][*] and store raw pointers
        for (k = 0; k < idxhlrddd; ++k)
        {
            B_hat[i][k].SetLength(d_hat);
            abc_reps[p++] = B_hat[i][k].rep.elts();
        }

        // Initialize all polynomials in C_hat[i][*] and store raw pointers
        for (k = 0; k < t_d; ++k)
        {
            C_hat[i][k].SetLength(d_hat);
            abc_reps[p++] = C_hat[i][k].rep.elts();
        }

        assert(p == m1);

        for (j = 0; j < 256; ++j)
        {
            ternary_sigma_accumulate_gamma(
                R_goth[j],
                gamma[i][j],
                abc_reps,
                m1
            );
        }
    }

    #ifdef ENABLE_TIMING_VERIFY
    double tA_2 = GetWallTime();
    #endif  

    // --------------------
    // A_hat update from P
    // Optimized loop order: j -> i -> k
    // --------------------
    for (j = 0; j < d0; ++j)
    {
        const vec_zz_p& Pj = P[j];

        for (i = 0; i < tau_ISIS; ++i)
        {
            const vec_zz_p& gamma_i = gamma[i];
            const zz_p& g = gamma_i[256 + j];
            poly_off = 0;

            for ( k = 0; k < m2ddd; ++k, poly_off += d_hat)
            {
                zz_pX& poly = A_hat[i][k];
                zz_p* rep = poly.rep.elts();

                const zz_p* src = &Pj[poly_off];

                rep[0] += g * src[0];

                t = 1;
                const zz_p* s = src + (d_hat - 1);

                for (; t + 3 < d_hat; t += 4, s -= 4)
                {
                    rep[t]     -= g * s[0];
                    rep[t + 1] -= g * s[-1];
                    rep[t + 2] -= g * s[-2];
                    rep[t + 3] -= g * s[-3];
                }

                for (; t < d_hat; ++t, --s)
                {
                    rep[t] -= g * (*s);
                }
            }
        }
    }

    #ifdef ENABLE_TIMING_VERIFY
    double tA__2 = GetWallTime();
    #endif
    for ( j = 0; j < d0; ++j)
    {
        const vec_zz_p& Cj  = C[j];
        

        for (i = 0; i < tau_ISIS; ++i)
        {
            poly_off = c_offset;
            const vec_zz_p& gamma_i = gamma[i];
            const zz_p& g = gamma_i[256 + j];

            // --------------------
            // B_hat update from C
            // --------------------
            for ( k = 0; k < idxhlrddd; ++k, poly_off += d_hat)
            {
                zz_pX& poly = B_hat[i][k];
                zz_p* rep = poly.rep.elts();

                const zz_p* src = &Cj[poly_off];

                rep[0] -= g * src[0];

                t = 1;
                const zz_p* s = src + (d_hat - 1);

                for (; t + 3 < d_hat; t += 4, s -= 4)
                {
                    rep[t]     += g * s[0];
                    rep[t + 1] += g * s[-1];
                    rep[t + 2] += g * s[-2];
                    rep[t + 3] += g * s[-3];
                }

                for (; t < d_hat; ++t, --s)
                {
                    rep[t] += g * (*s);
                }
            }  
        }
    }
    #ifdef ENABLE_TIMING_VERIFY
    double tA___2 = GetWallTime();
    #endif
    for ( j = 0; j < d0; ++j)
    {
        
        const vec_zz_p& Bfj = B_f[j];
        
        for (i = 0; i < tau_ISIS; ++i)
        {
            const vec_zz_p& gamma_i = gamma[i];
            const zz_p& g = gamma_i[256 + j];
            poly_off = 0;
            // ---------------------
            // C_hat update from B_f
            // ---------------------
            for ( k = 0; k < t_d; ++k, poly_off += d_hat)
            {
                
                zz_pX& poly = C_hat[i][k];
                zz_p* rep = poly.rep.elts();

                const zz_p* src = &Bfj[poly_off];

                rep[0] -= g * src[0];

                t = 1;
                const zz_p* s = src + (d_hat - 1);

                for (; t + 3 < d_hat; t += 4, s -= 4)
                {
                    rep[t]     += g * s[0];
                    rep[t + 1] += g * s[-1];
                    rep[t + 2] += g * s[-2];
                    rep[t + 3] += g * s[-3];
                }

                for (; t < d_hat; ++t, --s)
                {
                    rep[t] += g * (*s);
                }
            }
        }
    }


    #ifdef ENABLE_TIMING_VERIFY
    double tA_3 = GetWallTime();
    #endif

    for(i=0; i<tau_ISIS; i++)
    {

        zz_p &m = gamma[i][256+d0+2];
        for (k = 0; k < t_d; k++)
        {
            zz_pX &poly = C_hat[i][k];

            poly.rep[0] -= m;

            for (t = 1; t < d_hat; t++)
            {
                poly.rep[t] += m;
            }
        }
    }

    
    #ifdef ENABLE_TIMING_VERIFY
    double tA_4 = GetWallTime();
    cout << "FIRST part A,B,C: " << tA_2-tA_1 << endl;
    cout << "A_hat and P: " << tA__2-tA_2 << endl;
    cout << "B_hat and C " << tA___2-tA__2 << endl;
    cout << "C_hat and B_f " << tA_3-tA___2 << endl;
    cout << "SECOND part A,B,C: " << tA_3-tA_2 << endl;
    cout << "WHOLE A,B,C: " << tA_3-tA_1 << endl;
    cout << "LAST part C_hat: " << tA_4-tA_3 << endl;
    #endif

    #ifdef ENABLE_TIMING_VERIFY
    double tL_1 = GetWallTime();
    #endif
    // 19. Construction of L^ ∈ R^^(τ × (256/d_hat))_(q_hat)
    L_hat.SetDims(tau_ISIS, n256);
    
    for(i=0; i<tau_ISIS; i++)
    {
        poly_off = 0;
        const vec_zz_p &g_i = gamma[i];
        for (k=0; k<n256; k++, poly_off += d_hat)
        {
            zz_pX &poly = L_hat[i][k];
            poly.SetLength(d_hat);
            zz_p* rep = poly.rep.elts();
  
            rep[0] += g_i[poly_off];
            for(t=1; t<d_hat; t++){
                coeff_off = d_hat - t;
                rep[coeff_off] -= g_i[poly_off + t];
            }
        }
    }
    #ifdef ENABLE_TIMING_VERIFY
    double tL_2 = GetWallTime();
    #endif
    // 20. Definition of d_0 ∈ R^_(q_hat)
    clear(d_0);
    // NOTE: d_0 (not d0 parameter)
    
    for(i=0; i<tau_ISIS; i++)
    {
        const vec_zz_p &g_i = gamma[i];

        sums = g_i[0] * Pi.z_3[0];;
    
        for(j=1; j<256; j++)
        {
            sums += g_i[j] * Pi.z_3[j];
        }

        for(j=0; j<d0; j++)
        {
            sums += g_i[256+j] * m_C[j];
        }

        sums += g_i[256+d0] * B_goth_s2_p + g_i[256+d0+1] * B_goth_r2_p;

        d_0 = d_0 - ModPhi_hat_q( mu[i] * ( sums + Pi.h[i] ));
    }

    // for(i = 0; i < tau_ISIS / 2; i++)
    // {
    //     zz_pX sums;
    //     clear(sums);
    //     sums.SetLength(d_hat);

    //     for(j = 0; j < 256; j++)
    //     {
    //         sums[0] += gamma[2*i][j] * Pi.z_3[j];
    //     }

    //     for(j = 0; j < d0; j++)
    //     {
    //         sums[0] += gamma[2*i][256 + j] * m_C[j];
    //     }

    //     sums[0] += gamma[2*i][256 + d0]     * B_goth_s2_p;
    //     sums[0] += gamma[2*i][256 + d0 + 1] * B_goth_r2_p;


    //     for(j = 0; j < 256; j++)
    //     {
    //         sums[d_hat / 2] += gamma[2*i + 1][j] * Pi.z_3[j];
    //     }

    //     for(j = 0; j < d0; j++)
    //     {
    //         sums[d_hat / 2] += gamma[2*i + 1][256 + j] * m_C[j];
    //     }

    //     sums[d_hat / 2] += gamma[2*i + 1][256 + d0]     * B_goth_s2_p;
    //     sums[d_hat / 2] += gamma[2*i + 1][256 + d0 + 1] * B_goth_r2_p;

    //     d_0 = d_0 - ModPhi_hat_q(mu[i] * (sums + Pi.h[i]));
    // }

    #ifdef ENABLE_TIMING_VERIFY
    double tL_3 = GetWallTime();
    #endif
    // 21.  if one of the 4 conditions below does not hold, then return 0
    // Compute ||z_i||^2, squared Euclidean norm of each z_i
    norm2_z1 = Norm2Xm(Pi.z_1, d_hat, q2_hat);
    norm2_z2 = Norm2Xm(Pi.z_2, d_hat, q2_hat);
    norm2_z3 = Norm2m( Pi.z_3, q2_hat );
    // NOTE: norms computed using values in {-(q-1)/2, ..., (q-1)/2}

    // 21.1 First condition: ||z_1|| ≤ B_goth_1, ||z_2|| ≤ B_goth_2, ||z_3|| ≤ B_goth_3
    // NOTE: equations in ZZ, with squared norms and thresholds
    if ( norm2_z1 > B_goth2_1)
    {
        cout << "First condition failed - Invalid z_1 norm!" << endl;
        return 0;
    }

    if ( norm2_z2 > B_goth2_2)
    {
        cout << "First condition failed - Invalid z_2 norm!" << endl;
        return 0;
    }

    if ( norm2_z3 > B_goth2_3)
    {
        cout << "First condition failed - Invalid z_3 norm!" << endl;
        return 0;
    }

    #ifdef ENABLE_TIMING_VERIFY
    double tL_4 = GetWallTime();
    #endif

    // 21.2 Second condition: h˜_i == 0 for i ∈ [τ]
    // NOTE: equations in R^^_(q_hat)
    for(i=0; i<tau_ISIS; i++)
    {
        if ( coeff(Pi.h[i], 0) != 0 )
        {
            cout << "Second condition failed!" << endl;
            // cout <<  "h = " << Pi.h << endl;
            return 0;
        }
    }

    #ifdef ENABLE_TIMING_VERIFY
    double tL_5 = GetWallTime();
    #endif

    // 21.3 Third condition: A_1*z_1 + A_2*z_2 == w + c*t_A
    // NOTE: equations in R^^(n)_(q_hat)

    // for(i=0; i<n; i++)
    // {

    //     // A_1*z_1 + A_2*z_2,
    //     acc = poly_mult_hat_opt(crs[0][i], Pi.z_1) + poly_mult_hat_opt(crs[1][i], Pi.z_2);
        
    //     // w + c*t_A
    //     acc2 = Pi.w[i] + ModPhi_hat_q( c * Pi.t_A[i] );
  
    //     if (acc != acc2)
    //     {
    //         cout << "Third condition failed!" << endl;
    //         return 0;
    //     }
    // }

    for (i = 0; i < n; ++i)
    {
        poly_mult_hat_opt_to(acc, crs[1][i], Pi.z_2, scratch_poly);
        poly_mult_hat_opt_to(product1, crs[0][i], Pi.z_1, scratch_poly);
        add(acc, acc, product1);

        mul(product2, c, Pi.t_A[i]);
        ModPhi_hat_q_inplace(product2);

        add(acc2, Pi.w[i], product2);

        if (acc != acc2)
        {
            cout << "Third condition failed!" << endl;
            return 0;
        }
    }
    
    #ifdef ENABLE_TIMING_VERIFY
    double tL_6 = GetWallTime();
    cout << "L_hat: " << tL_2-tL_1 << endl;
    cout << "d_0 " << tL_3-tL_2 << endl;
    cout << "first condition: " << tL_4-tL_3 << endl;
    cout << "second condition: " << tL_5-tL_4 << endl;
    cout << "third condition: " << tL_6-tL_5 << endl;
    #endif

    // 21.4 Fourth condition: (Sum1) + (Sum2) + c^2*d_0 − (c*t − b^T*z_2) == f0
    // NOTE: equations in R^^_(q_hat)

    // 1st addend Sum1 = Sum_(i=1,τ){ μ_i · ( δ1*z[3]z[0] + δ2*z[4]z[1] + δ3*z[5]z[2] )}
    // NOTE: precompute z[3]z[0], z[4]z[1], z[5]z[2], considering the following sizes:
    //
    //  z[0]    z[1]     z[2]  z[3]     z[4]    z[5] z[6]    z[7]
    // m2ddd, idxhlrddd, t_d, m2ddd, idxhlrddd, t_d, n256, tau_ISIS
    //           m1          |           m1        | n256, tau_ISIS
    
    #ifdef ENABLE_TIMING_VERIFY
    double t__1 = GetWallTime();
    #endif
    z3z0.SetLength(d_hat);
    z4z1.SetLength(d_hat);
    z5z2.SetLength(d_hat);
    sum.SetLength(d_hat);

    // -----------------------------------------------------------------------------
    // z3z0 = sum_{i=0}^{m2ddd-1} sigma(z_1[i]) * z_1[i]
    // -----------------------------------------------------------------------------

    sigma_poly(sigma_tmp, Pi.z_1[0], d_hat);
    mul( z3z0, sigma_tmp, Pi.z_1[0]);
    for (i = 1; i < m2ddd; ++i)
    {
        sigma_poly( sigma_tmp, Pi.z_1[i], d_hat);
        mul( product1, sigma_tmp, Pi.z_1[i]);
        add( z3z0, z3z0, product1);
    }
    ModPhi_hat_q_inplace(z3z0);
    

    // -----------------------------------------------------------------------------
    // z4z1 = sum_{i=m2ddd}^{m2ddd+idxhlrddd-1}
    //         sigma(z_1[i]) * z_1[i]
    // -----------------------------------------------------------------------------

    sigma_poly( sigma_tmp, Pi.z_1[m2ddd], d_hat);
    mul( z4z1, sigma_tmp, Pi.z_1[m2ddd]);
    for (i = m2ddd + 1; i < m2ddd + idxhlrddd; ++i)
    {
        sigma_poly( sigma_tmp, Pi.z_1[i], d_hat);
        mul( product1, sigma_tmp, Pi.z_1[i]);
        add( z4z1, z4z1, product1);
    }
    ModPhi_hat_q_inplace(z4z1);

    // -----------------------------------------------------------------------------
    // z5z2 = sum_{i=m2ddd+idxhlrddd}^{m1-1}
    //         sigma(z_1[i]) * z_1[i]
    // -----------------------------------------------------------------------------

    sigma_poly( sigma_tmp, Pi.z_1[m2ddd+idxhlrddd], d_hat);
    mul( z5z2, sigma_tmp, Pi.z_1[m2ddd+idxhlrddd]);
    for (i = m2ddd+idxhlrddd + 1; i < m1; ++i)
    {
        sigma_poly(sigma_tmp, Pi.z_1[i], d_hat);

        mul(product1, sigma_tmp, Pi.z_1[i]);
        add(z5z2, z5z2, product1);
    }
    ModPhi_hat_q_inplace(z5z2);

    #ifdef ENABLE_TIMING_VERIFY
    double tl2 = GetWallTime();
    #endif
    
    mul(delta_1, mu[0], gamma[0][256 + d0]);
    mul(delta_2, mu[0], gamma[0][256 + d0 + 1]);
    mul(delta_3, mu[0], gamma[0][256 + d0 + 2]);

    for (i = 1; i < tau_ISIS; ++i)
    {
        const vec_zz_p &g_i = gamma[i];

        mul(product1, mu[i], g_i[256 + d0]);
        add(delta_1, delta_1, product1);

        mul(product1, mu[i], g_i[256 + d0 + 1]);
        add(delta_2, delta_2, product1);

        mul(product1, mu[i], g_i[256 + d0 + 2]);
        add(delta_3, delta_3, product1);
    }

    mul(product1, delta_1, z3z0);
    mul(product2, delta_2, z4z1);
    add(product1, product1, product2);

    mul(product2, delta_3, z5z2);
    add(product1, product1, product2);

    ModPhi_hat_q_inplace(product1);
    add(sum, sum, product1);

    // for (i = 0; i < tau_ISIS; i++)
    // {
    //     sum += ModPhi_hat_q(
    //         mu[i] *
    //         (
    //             gamma[i][256 + d0] * z3z0 +
    //             gamma[i][256 + d0 + 1] * z4z1 +
    //             gamma[i][256 + d0 + 2] * z5z2
    //         )
    //     );
    // }

    // 2nd addend Sum2 = Sum_(i=1,τ){ μ_i · c · ( a_i*z[0] + b_i*z[1] + c_i*z[2] + l_i*z[6] + z[7]_i )}
    
    #ifdef ENABLE_TIMING_VERIFY
    double tl3 = GetWallTime();
    #endif

    acc.SetLength(d_hat);
    
    for(i=0; i<tau_ISIS; i++)
    {
        const vec_zz_pX &a_i = A_hat[i];
        const vec_zz_pX &b_i = B_hat[i];
        const vec_zz_pX &c_i = C_hat[i];
        const vec_zz_pX &l_i = L_hat[i];
        // a_i*z[0]
        mul(acc, a_i[0], Pi.z_1[0]); 
        for(k=1; k<(m2ddd); k++)
        {
            mul(product1, a_i[k], Pi.z_1[k]);
            add(acc, acc, product1);
        }

        // + b_i*z[1]
        for(k=0; k<(idxhlrddd); k++)
        {
            mul(product1, b_i[k], Pi.z_1[m2ddd + k]);
            add(acc, acc, product1);
        }

        // + c_i*z[2]
        for(k=0; k<(t_d); k++)
        {
            mul(product1, c_i[k], Pi.z_1[m2ddd+idxhlrddd + k]);
            add(acc, acc, product1);
        }

        // + l_i*z[6]
        for(k=0; k<(n256); k++)
        {
            mul(product1, l_i[k], z[k]);
            add(acc, acc, product1);  
        }

        add(acc, acc, z[n256+i]);  
        ModPhi_hat_q_inplace(acc);
        mul(product1, acc, c);
        ModPhi_hat_q_inplace(product1);
        mul(product1, mu[i], product1);
        ModPhi_hat_q_inplace(product1);
        add(sum, sum, product1);
        // sum += ModPhi_hat_q( mu[i] * ModPhi_hat_q( c * acc ) );
    }

    // acc.SetLength(d_hat);
    // for(i=0; i<tau_ISIS; i++)
    // {
    //     acc = A_hat[i][0] * Pi.z_1[0];

    //     for(k=1; k<(m2ddd); k++)
    //     {
    //         acc += A_hat[i][k] * Pi.z_1[k]; // a_i*z[0]
    //     }

    //     for(k=0; k<(idxhlrddd); k++)
    //     {
    //         acc += B_hat[i][k] * Pi.z_1[m2ddd + k]; // + b_i*z[1]
    //     }

    //     for(k=0; k<(t_d); k++)
    //     {
    //         acc += C_hat[i][k] * Pi.z_1[m2ddd+idxhlrddd + k]; // + c_i*z[2]
    //     }

    //     for(k=0; k<(n256); k++)
    //     {
    //         acc += L_hat[i][k] * z[k]; // + l_i*z[6]
    //     }
    //     acc += z[n256+i];
    //     acc = ModPhi_hat_q(acc);
    //     sum += ModPhi_hat_q( mu[i] * ModPhi_hat_q( c * acc ) );
    // }


    #ifdef ENABLE_TIMING_VERIFY
    double tl4 = GetWallTime();   
    #endif

    // 3rd addend (c^2 * d_0)
    product1 = sqr(c);
    ModPhi_hat_q_inplace(product1);
    mul(product1, product1, d_0  );
    ModPhi_hat_q_inplace(product1);
    add(sum, sum, product1 );
    // sum += ModPhi_hat_q( ModPhi_hat_q( sqr(c) ) * d_0 );

    // 4rd addend −(c*t − b^T * z_2)
    //sum -= ( ModPhi_hat_q( c * Pi.t ) - poly_mult_hat(crs[4][0], Pi.z_2) );

    mul(product1, c, Pi.t);
    ModPhi_hat_q_inplace(product1);

    poly_mult_hat_opt_to(product2, crs[4][0], Pi.z_2, scratch_poly);

    sub(tmp_sub, product1, product2);   // tmp_sub = c*t - b^T*z_2
    sub(sum, sum, tmp_sub); // sum -= tmp_sub
    if (sum != Pi.f0)
    {
        cout << "Fourth condition failed!" << endl;
        // cout << sum << " != " << Pi.f0 << endl;
        return 0;
    }

    // cout << "# Verify_ISIS: OK!" << endl;

    // 22. else, return 1
    #ifdef ENABLE_TIMING_VERIFY
    double tl5 = GetWallTime();   
    // cout << "σ(Pi.z_1[i]) + setDims: " << t__2-t__1 << endl;
    // cout << "z3z0: " << t__3-t__2 << endl;
    // cout << "z4z1: " << t__4-t__3 << endl;
    // cout << "z5z2: " << tl2-t__4 << endl;
    cout << "z3z0,z4z1,z5z2: " << tl2-t__1 << endl;
    cout << "loop delta: " << tl3-tl2 << endl;
    cout << "loop acc linear part: " << tl4-tl3 << endl;
    cout << "loop sum: " << tl5-tl4 << endl;
    #endif

    return 1;  
}
